my_blog/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('', views.home, name='homepage'),
    path('<slug:post>/', views.post_info, name='post_info'),
    path('<int:post_id>/share/', views.share, name='share'),
    path('login', views.login, name='login'),
    path('tag/<slug:tag_slug>/', views.home, name='post_list_by_tag'),
    path('logout', views.logout, name='logout'),
]

my_blog/my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import BlogpostResource

post_resource = BlogpostResource()


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('api/', include(post_resource.urls)),
]

my_blog/blog/models.py
from urllib import request
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset()\
                        .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                                related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                                default='draft')

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    def get_absolute_url(self):
        return reverse("blog:post_info", args=[
                        self.slug])                        
    

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    tags = TaggableManager()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                                related_name='comments')
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

my_blog/blog/forms.py
from django import forms
from .models import Comment

class EmailPosts(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comment = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')


my_blog/blog/views.py
from pyexpat.errors import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as user_login
from django.contrib.auth import logout as user_logout
from django.contrib import messages
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPosts, CommentForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count

app_name = 'blog'

# Create your views here.
def landing(request):
    """rendering the homepage of my blog"""
    return render(request, 'blog/landing.html')


def login(request):
    """loading the login page"""
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            user_login(request, user)
            return redirect('blog:homepage')
        else:
            messages.info(request, 'Invalid username or password')
            return redirect('blog:login')
    else:
        return render(request, 'blog/login.html')

def logout(request):
    """Login user out of the system"""
    user_logout(request)
    return redirect('blog:homepage')


def signup(request):
    """function for serving signup/signin as well as authentication of password"""
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['repeat_password']

        if password == password2:
            if User.objects.filter(email=email).exists():
                """check whether email is already used"""
                messages.info(request, 'Email Already Exists')
                return redirect('blog:signup')
            elif User.objects.filter(username=username).exists():
                """check whether username is already used"""
                messages.info(request, 'Username Already Used')
                return redirect('blog:signup')
            else:
                """if details provided are unique create and save user to database"""
                user = User.objects.create_user(username=username, email=email, password=password)
                user.save();
                return redirect('blog:login')
        else:
            messages.info(request, 'Password does not match')
            return redirect('blog:signup')

    else:
        return render(request, 'blog/signup.html')


def home(request, tag_slug=None):
    """Function for serving the list of posts from database to homepage"""
    post_objects = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_objects = post_objects.filter(tags__in=[tag])
    #adding pagination to my blog page and setting a max of 3 post per page
    paginator = Paginator(post_objects, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/home.html', {'posts': posts,'page': page, 'tag': tag})

def post_info(request, post):
    """function for serving the entire post"""
    post = get_object_or_404(Post,
                                slug=post, status='published')
    #active comments
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Creating a comment obj
            new_comment = comment_form.save(commit=False)
            # Assign current post to comment
            new_comment.post = post
            #save comment to db
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]

    return render(request, 'blog/post.html', {'post': post, 'similar_posts': similar_posts,
                    'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})


def share(request, post_id):
    #currntly not working
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPosts(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"""{data['name']} recommends you read
                        {post.title}"""
            message = f"Read {post.title} at {post_url}\n\n" \
                        f"{data['name']}\'s comments: {data['comments']}"
            send_mail(subject, message, 'email@gmail.com',[data['to']])
            sent = True
    else:
        form = EmailPosts()
    return render(request, 'blog/share.html', {'form': form, 'post': post, 'sent': sent})

my_blog/blog/templates/blog/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='{% static "css/home/bootstrap.min.css" %}' rel='stylesheet'>
    <link href="{% static 'css/home/style.css' %}" rel='stylesheet'>
	<title></title>
</head>
<body>
  <ul>
    {% if user.is_authenticated %}
    <li><a href={% url 'blog:homepage' %}>Welcome, {{user.username}}</a></li>
    <li>
      <a href={% url 'blog:logout' %}>Logout</a>
    </li>
    <li><a href="#">About us</a></li>
    <li><a href="#">Contact us</a></li>
    {% else %}
    <li><a href={% url 'blog:homepage' %}>Home</a></li>
    <li>
      <a href="#">Signup or Login</a>
      <ul class="dropdown">
        <li><a href={% url 'blog:signup' %}>Signup</a></li>
        <li><a href={% url 'blog:login' %}>Login</a></li>
      </ul>
    </li>
    <li><a href="#">About us</a></li>
    <li><a href="#">Contact us</a></li>
    {% endif %}
  </ul>
<main class="main-content">
	<article class="content">
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
      {% for post in posts %}
      <div class="post">
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        <p class="author">by <a href="#">{{ post.author }}</a> published {{ post.publish }}</p>
        <p>{{ post.body|truncatewords:50|linebreaks }}</p>
          <footer>
            <a href="{{ post.get_absolute_url }}" class="more-link">Read More</a>
          </footer>
    </div>
    <hr>
	  {% endfor %}
	</article>
	<section class="sidebar">
        <div>
		<h3>Popular posts</h3>
        <div>
	</section>
</main>
<footer class="footer">
	<div id="pagination">
        {% if posts.has_previous %}
        <a class="next page-numbers" href="?page={{ posts.previous_page_number }}">« Previous</a>
        {% else %}
        <a class="next page-numbers" href="#">« Previous</a>
        {% endif %}
        <span class="page-numbers current">{{ posts.number }}</span>
        {% if posts.has_next %}
        <a class="next page-numbers" href="?page={{ posts.next_page_number }}">Next »</a>
        {% else %}	
        <a class="next page-numbers" href="#">Next »</a>
        {% endif %}
    <div>
</footer>
<!--js-->
<script type="text/javascript" src="{% static 'js/home/script.js' %}"></script>
</body>
</html>

my_blog/blog/templates/blog/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/signup/style.css' %}">
    <title>Login</title>
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/295/295128.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>

<body>
    <div class="container">
        <div class="container-wrapper">

            <h3 class="login-text"><i class="bi bi-person-circle ac-logo"></i>Login</h3>
            {% for message in messages %}
            <h5 style='color: red; text-align: center'>{{message}}</h5>
            {% endfor %}
            <form method="POST" action=''>
                {% csrf_token %}
                <div class="item"><input class="input" type="text" placeholder="Username" name='username'></div> 
                <div class="item"><input class="input" type="password" placeholder="Password" name='password'> </div>
                <span class="remember"> <a href="#">Forgot Password?</a> </span>

                <div class="item submit"><button type="submit">Submit</button></div>
            </form>
            <h2><span>OR</span></h2>
         
            <div class="social-media">

                <a href="#"><div class="icons8-google social-mediaImg"></div></a> 
                <a href="#"><div class="icons8-facebook-circled social-mediaImg"></div></a> 
                <a href="#"><div class="icons8-twitter social-mediaImg"></div></a> 
  
            </div>
            <span class="ac">Don't have an Account? <a href={% url 'blog:signup' %}>Sign Up</a></span>
        </div>

    </div>
  
</body>
</html>

my_blog/blog/templates/blog/post.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>Home</title>
<link rel="stylesheet" href="{% static 'css/home/style.css' %}">

</head>
<body>
  <ul>
    {% if user.is_authenticated %}
    <li><a href={% url 'blog:homepage' %}>Welcome, {{user.username}}</a></li>
    <li>
      <a href={% url 'blog:logout' %}>Logout</a>
    </li>
    <li><a href="#">About us</a></li>
    <li><a href="#">Contact us</a></li>
    {% else %}
    <li><a href={% url 'blog:homepage' %}>Home</a></li>
    <li>
      <a href="#">Signup or Login</a>
      <ul class="dropdown">
        <li><a href={% url 'blog:signup' %}>Signup</a></li>
        <li><a href={% url 'blog:login' %}>Login</a></li>
      </ul>
    </li>
    <li><a href="#">About us</a></li>
    <li><a href="#">Contact us</a></li>
    {% endif %}
  </ul>
<main class="main-content">
	<article class="content">
      <div class="post" id='post-spec'>
        <h2>{{ post.title }}</h2>
		<p class="tags">
 			Tags:
 			{% for tag in post.tags.all %}
 			<a href="{% url "blog:post_list_by_tag" tag.slug %}">
 			{{ tag.name }}
 			</a>
 			{% if not forloop.last %}, {% endif %}
 			{% endfor %}
		</p>
        <p class="author">by {{ post.author }} published {{ post.publish }}</p>
        <p>{{ post.body|linebreaks }}</p>
        <hr>
        <a href="{% url "blog:share" post.id %}" class='share-btn'>Share this post</a>

		<!--Comment section-->
		<div class='parent'>
		{% with comments.count as total_comments %}
 		<h2 id='comment-count'>
 		{{ total_comments }} comment{{ total_comments|pluralize }}
 		</h2>
		<div class="comment">
		{% for comment in comments %}
 		<p class="author">
 		Comment {{ forloop.counter }} by {{ comment.name }}
 		{{ comment.created }}
 		</p>
 		{{ comment.body|linebreaks }}
 		
		{% empty %}
 		<p>There are no comments yet.</p>
		{% endfor %}
		</div>
		{% endwith %}

		<div class='new_comment'>
		{% if new_comment %}
 		<h2>Your comment has been added.</h2>
		{% else %}
 		<h3>Add a new comment</h3>
 		<form method="post">
 		{{ comment_form.as_p }}
 		{% csrf_token %}
 		<p><input type="submit" value="Add comment"></p>
 		</form>
		{% endif %}
		</div>
		</div>
    </div>
	</article>
	<section class="sidebar">
		<h3>Similar Posts</h3>
		{% for post in similar_posts %}
 		<ul>
 		<li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
		</ul>
		{% empty %}
 		There are no similar posts yet.
		{% endfor %}
		<h3>Popular posts</h3>

	</section>
</main>
<!--js-->
<script type="text/javascript" src="./bootstrap.min.js"></script>
</body>
</html>




my_blog/blog/templates/blog/share.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>share post</title>
</head>
<body>
{% if sent %}
 <h1>E-mail successfully sent</h1>
 <p>
 "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
 </p>
 {% else %}
 <h1>Share "{{ post.title }}" by e-mail</h1>
 <form method="POST">
 {{ form.as_p }}
 {% csrf_token %}
 <input type="submit" value="Send e-mail">
 </form>
 {% endif %}
</body>
</html>

my_blog/blog/templates/blog/signup.html
{%load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/signup/style.css' %}">
    <title>Signup</title>
    <link rel="shortcut icon" href="https://cdn-icons-png.flaticon.com/512/295/295128.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
</head>

<body>
    <div class="container">
        <div class="container-wrapper">

            <h3 class="login-text"><i class="bi bi-person-circle ac-logo"></i>Signup</h3>
			{% for message in messages %}
			<h5 style='text-align: center;color: red'>{{ message }}</h5>
			{% endfor %}
            <form method="POST" action='signup'>
				{% csrf_token %}
                <div class="item"><input class="input" type="text" placeholder="Username" name='username'></div> 
                <div class="item"><input class="input" type="text" placeholder="Email" name='email'></div> 
                <div class="item"><input class="input" type="password" placeholder="Password" name='password'> </div>
                <div class="item"><input class="input" type="password" placeholder="Repeat Password" name='repeat_password'> </div>
                <div class="item submit"><button type="submit">Submit</button></div>
            </form>
            <h2><span>OR</span></h2>
         
            <div class="social-media">

                <a href="#"><div class="icons8-google social-mediaImg"></div></a> 
                <a href="#"><div class="icons8-facebook-circled social-mediaImg"></div></a> 
                <a href="#"><div class="icons8-twitter social-mediaImg"></div></a> 
  
            </div>
            <span class="ac">Already have an Account? <a href={% url 'blog:login' %}>Login</a></span>
        </div>

    </div>
</body>

</html>